spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cafe_auth}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
