server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # Usuarios
        - id: usuarios-service
          uri: lb://USUARIOS-SERVICE
          predicates:
            - Path=/usuarios/**

        # Reservas
        - id: reserva-service
          uri: lb://RESERVA-SERVICE
          predicates:
            - Path=/reservas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true